apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tang-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tang-operator
    app.kubernetes.io/part-of: tang-operator
  name: tang-operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: tang-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: tang-operator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sarroutb-tenant/tang-operator/tang-operator@sha256:2f0473cd2e34a3e05b8b2a1953769a46fe65121b99a4fd4667f9c1ea7ff3783f
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
